### ISSUE TITLE
Setting "Grant ability" as a card mechanic in the card editor permanently crashes the editor

### ISSUE THREAD

**Issue by Iunnolol** [Fifth-Aeon/Fifth-Aeon-Model#23]
Relatedly, any decks holding these cards no longer appear.

**Comment by WilliamRitson** [comment]
Thanks you @Iunnolol  for the bug report.

The problem was that the GrantAbility mechanic requires an ability constructor to be passed in as a parameter which wasn't something the editor supported. 

I added support for an ability parameter type to the editor in https://github.com/Fifth-Aeon/Fifth-Aeon-Model/commit/7c4013830b2c9149270528abe7b195e56cdbc682. The editor should no longer crash and should now be possible to actually use GrantAbility on custom cards.
